version: '2'
services:
  server:
    build:
      context: ./
    command: npm run server
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
      - /usr/app/build
    ports:
      - "80:80"
      - "443:443"
    environment:
      CONNECTION_STRING_DEV: postgres://user:password@db/db
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SERVICE: ${MAIL_SERVICE}
      PUBLIC_URL: https://localhost
      NODE_ENV: ${NODE_ENV}
